[versions]

# mflisar
kmp-gradle-tools =              "1.5.0"

# ---------
# plugins
# ---------

[plugins]

# mflisar
kmp-gradle-tools-build-gradle-plugin =          { id = "io.github.mflisar.kmp-gradle-tools.build-gradle-plugin",                    version.ref = "kmp-gradle-tools" }

# ---------
# libraries
# ---------

[libraries]