[versions]

# mflisar
kmp-gradle-tools =              "1.5.0" # attention: the version for the settings plugin must be adjusted manually!

# ---------
# plugins
# ---------

[plugins]

# mflisar
kmp-gradle-tools-build-gradle-plugin =          { id = "io.github.mflisar.kmp-gradle-tools.build-gradle-plugin",                    version.ref = "kmp-gradle-tools" }

# ---------
# libraries
# ---------

[libraries]

# mflisar
kmp-gradle-tools-scripts =                      { module = "io.github.mflisar.kmp-gradle-tools:scripts",                            version.ref = "kmp-gradle-tools" }
kmp-gradle-tools-docs =                         { module = "io.github.mflisar.kmp-gradle-tools:docs",                               version.ref = "kmp-gradle-tools" }